# Sources configuration
source 'https://cdn.cocoapods.org/'

platform :ios
use_frameworks!

# Plugins

plugin 'cocoapods-spm'

# Pods used in multiple targets

target 'interop-plugin-spm' do

    pod 'interop-plugin-spm', :path => './'
    spm_pkg 'NetworkMonitor', :url => 'https://github.com/Farfetch/network-monitor-ios.git', :version => '12.1.0'
end