# Sources configuration
source 'https://cdn.cocoapods.org/'

platform :ios
use_frameworks!

# Plugins

plugin 'cocoapods-spm'

# Pods used in multiple targets

# NetworkMonitor is to be use in both main & test targets
spm_pkg 'NetworkMonitor', :url => 'https://github.com/Farfetch/network-monitor-ios.git', :version => '12.1.0'

target 'interop-plugin-spm' do
    pod 'interop-plugin-spm', :path => './'
end

target 'interop-plugin-spmTests' do
end
